name: ChatColorHandlerPaperTest
version: '${version}'
main: me.dave.chatcolorhandlerpapertest.ChatColorHandlerPaperTest
api-version: '1.20'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false